version: "3"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3306"
      - "3000"
      - "5000"
    command: "npm run dev"
    ports:
      - 3000:3000
      - 5000:5000